name: 'Release Card'
description: 'Generates a release card'
inputs:
  version:
    description: 'Version number'
    required: true
  contributor:
    description: 'Contributor name'
    required: true
  description_base64:
    description: 'Release description (base64 encoded)'
    required: true
  repo_name:
    description: 'Repository name'
    required: false
runs:
  using: 'docker'
  image: 'docker://mmorepan/release-cards:main'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.contributor }}
    - ${{ inputs.description_base64 }}
    - ${{ inputs.repo_name }}
